[version]
current = "0.1.3"

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump dask-gateway to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "Makefile"
search = "VERSION = {current_version}"

[[after_push]]
name = "Update changelog"
cmd = "make changelog; git add changelog.md; git commit -m 'Updates changelog'"
