[version]
current = "0.1.7"

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump earth-science-notebook to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "Makefile"
search = "VERSION = {current_version}"

[[file]]
src = "../earth-science-notebook-gpu/Dockerfile"
search = "TAG={current_version}"
