[version]
current = "0.1.5"

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump climate-notebook-gpu to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "Makefile"
search = "VERSION = {current_version}"
