name: Containers

on:
  push:
    branches:
      - main
    paths:
      - 'dockerfiles/**'

  pull_request:
    branches:
      - main
    paths:
      - 'dockerfiles/**'

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-minimal-notebook:
    runs-on: ubuntu-latest
    name: Build minimal-notebook
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - id: get-version
        run: |
          pip install tbump
          pushd dockerfiles/minimal-notebook
          echo "version=$(tbump current-version)" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: dockerfiles/minimal-notebook
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/esgf-nimbus/minimal-notebook:${{ steps.get-version.outputs.version }}

  build-climate-notebook:
    needs:
      - build-minimal-notebook
    runs-on: ubuntu-latest
    name: Build climate-notebook
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - id: get-version
        run: |
          pip install tbump
          pushd dockerfiles/climate-notebook
          echo "version=$(tbump current-version)" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: dockerfiles/climate-notebook
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/esgf-nimbus/climate-notebook:${{ steps.get-version.outputs.version }}
